# Site wide configuration

title: IT-Beratung - Benjamin Herbert
locale: de_DE
description: Softwareentwicklung, Buildmanagement, Releasemanagement
logo: #site-logo.png
search: true
share: true
url: http://herbert.cc

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false
  input: GFM

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Benjamin Herbert
  avatar: bio-photo.jpg
  email: mail@herbert.cc
  disqus-shortname:
  twitter: NothingMatress
  xing: https://www.xing.com/profile/Benjamin_Herbert2
  facebook: #username
  github: BenjaminHerbert
  stackexchange: https://stackoverflow.com/users/1153530/behe
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics: UA-55191852-1
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
